name: healthcheck
on:
  push:
    branches:
      - $default-branch
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go test
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go build
