name: pullrequest
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - run: make dev-file
      - run: make dev-pipe
      - run: make lint
      - run: make test
      - run: make build-linux
      - run: make build-macos
