name: release
on:
  workflow_dispatch:
    inputs:
      method:
        required: true
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor' or 'patch'.
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: make lint
      - run: make test
      - run: make build-linux
      - run: make build-macos
  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kyoh86/git-vertag-action@v1.1
        with:
          # method: "major", "minor" or "patch" to update tag with semver
          method: "${{ github.event.inputs.method }}"
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}